### PR TITLE
Adds Pocket Support

### PR DESCRIPTION
**Pull request by ZachOrr**
Adds "Save to Pocket" as an option in the UIActivityViewController

PocketAPIActivity taken from here https://github.com/Pocket/Pocket-ObjC-SDK/pull/1

To get the functionality to work properly, you'll need to create two Pocket applications (one for the iPhone, one for the iPad) http://getpocket.com/developer/apps/

Modify the Constants.h file with the keys for each device. Additionally, inside the Info.plist file, you'll need to edit URL Types -> Item 0 -> URL Schemes -> Item 0 to be pocketappXXXX, where XXXX is the digits before the dash in your consumer keys

Ex: 

```
Consumer Key: 42-abcdef
pocketapp42
```

The one thing this pull request is missing is some indicator about successfully saving a link or a link failing to being saved. Right now there are just NSLogs. I figured a stock UIAlertView wouldn't fit the style of the app and would be too intrusive. Any suggestions?

### CODE REVIEW

**Comment by FredKSchott** [comment]
:+1:

**Comment by mmackh** [comment]
Thank you very much for this contribution - as for the successful saving to pocket, I don't think it needs any kind of notification, since the SDK redirects the user to their app. Will continue to think about something though.

Edit: Just saw that it doesn't redirect after I've authenticated the app

**Comment by ZachOrr** [comment]
Just tested it - it redirects fine for me

**Comment by mmackh** [comment]
My point was that it doesn't always redirect, but still saves the article i.e. giving the user no indication that the article was successfully saved.

**Comment by ZachOrr** [comment]
Aaah gotcha

-- 
Zachary Orr

On June 30, 2013 at 11:14:11 AM, Maximilian Mackh (notifications@github.com) wrote:

My point was that it doesn't always redirect, but still saves the article i.e. giving the user no indication that the article was successfully saved.

**Pull request merged**
